[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"
  # Clear flags to ensure --ignore-optional is not set
  YARN_FLAGS = "" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
